import { createBrain } from './bandBrain.js';

// Brain that plays bars generated by the FastAPI backend. The scheduler calls
// step() synchronously per grid step, so bars are fetched ahead of time and
// buffered; when the buffer runs dry (slow network / offline) it delegates to
// the local rule-based brain so the band never goes silent.

const ENDPOINT = import.meta.env.VITE_TRANSFORMER_URL || 'http://localhost:8000';

// backend event -> the event shape the scheduler renders
function toEngineEvents(rawEvents, ctx) {
  const out = [];
  for (const ev of rawEvents) {
    if (ev.kind === 'drum') {
      out.push({ kind: 'drum', drum: ev.drum, gain: ev.gain, dt: ev.dt || 0 });
    } else if (ev.kind === 'bass') {
      let semi = ev.semi;
      if (semi === 'third') semi = ctx.chordQuality === 'min' ? 3 : 4;
      out.push({
        kind: 'bass',
        semi,
        gain: ev.gain,
        sustain: (ev.sustainBeats ?? 1) * ctx.beatSec,
        dt: ev.dt || 0,
        slide: !!ev.slide,
      });
    }
  }
  return out;
}

export function createTransformerBrain({
  genre = 'rock', timeSig = '4/4', endpoint = ENDPOINT, lookahead = 2, lowWater = 1,
} = {}) {
  const fallback = createBrain({ genre, timeSig });
  let buffer = [];      // queued bars; each is { [step]: rawEvent[] }
  let curBar = null;
  let fetching = false;
  let context = { energy: 0.5, playerOnsets: 4, recentChords: [], tier: 1 };

  function indexByStep(events) {
    const byStep = {};
    for (const ev of events) (byStep[ev.step] ??= []).push(ev);
    return byStep;
  }

  async function prefetch() {
    if (fetching) return;
    fetching = true;
    try {
      const res = await fetch(`${endpoint}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ genre, timeSig, bars: lookahead, context }),
      });
      if (res.ok) {
        const data = await res.json();
        for (const bar of data.bars) buffer.push(indexByStep(bar.events));
      }
    } catch {
      /* offline — the fallback brain keeps the band playing */
    } finally {
      fetching = false;
    }
  }

  return {
    stepAdvance: (step) => fallback.stepAdvance(step),

    reset() {
      buffer = [];
      curBar = null;
      fallback.reset();
      prefetch();
    },

    step(ctx) {
      context = { energy: ctx.energy, playerOnsets: ctx.playerOnsets, recentChords: context.recentChords, tier: context.tier };
      if (ctx.step === 0) {
        curBar = buffer.shift() ?? null;
        if (buffer.length <= lowWater) prefetch();
      }
      if (!curBar) return fallback.step(ctx);
      return toEngineEvents(curBar[ctx.step] || [], ctx);
    },
  };
}
