import { useState } from 'react';
import styles from './ReportView.module.css';

function fmtTime(sec) {
  const m = Math.floor(sec / 60);
  const s = Math.round(sec % 60);
  return `${m}:${String(s).padStart(2, '0')}`;
}

const cap = (s) => s ? s[0].toUpperCase() + s.slice(1) : s;

function dynLabel(range) {
  return range > 0.5 ? 'Wide' : range > 0.25 ? 'Some' : 'Flat';
}

function pocketSub(t) {
  if (t.firstHalfPocketPct != null && t.secondHalfPocketPct != null) {
    if (t.secondHalfPocketPct >= t.firstHalfPocketPct + 5) return `tightened up ↑ (${t.firstHalfPocketPct}→${t.secondHalfPocketPct}%)`;
    if (t.firstHalfPocketPct >= t.secondHalfPocketPct + 5) return `eased off (${t.firstHalfPocketPct}→${t.secondHalfPocketPct}%)`;
  }
  return `±${t.spreadMs}ms spread`;
}

function feelSub(t) {
  if (t.tendency === 'steady') return 'right on the beat';
  return `~${Math.abs(t.medianOffsetMs)}ms ${t.tendency === 'rushing' ? 'early' : 'late'}`;
}

function Stat({ label, value, sub }) {
  return (
    <div className={styles.stat}>
      <div className={styles.statValue}>{value}</div>
      <div className={styles.statLabel}>{label}</div>
      {sub && <div className={styles.statSub}>{sub}</div>}
    </div>
  );
}

// ── Chord-chart export ──────────────────────────────────────────────────────
// The session captured the progression as you played it; turn it into a chart.

const BARS_PER_ROW = 4;

// "Key of A minor  ·  96 BPM  ·  4/4"
function chartMeta(report, timeSig) {
  const parts = [];
  if (report.key)   parts.push(`Key of ${report.key}`);
  if (report.tempo) parts.push(`${report.tempo.meanBpm} BPM`);
  if (timeSig)      parts.push(timeSig);
  return parts.join('  ·  ');
}

// plain-text chart for the clipboard: "| Am | F | C | G |"
function chordsToText(report, timeSig) {
  const seq  = report.chords?.sequence ?? [];
  const meta = chartMeta(report, timeSig);
  const lines = meta ? [meta, ''] : [];
  for (let i = 0; i < seq.length; i += BARS_PER_ROW) {
    lines.push('| ' + seq.slice(i, i + BARS_PER_ROW).join(' | ') + ' |');
  }
  return lines.join('\n');
}

// Draw the chart onto a canvas (branded, dark) so it can be saved/shared as an
// image. Colours mirror the app's CSS variables (see App/index.css).
function buildChartCanvas(report, timeSig) {
  const seq  = report.chords?.sequence ?? [];
  const cols = BARS_PER_ROW;
  const rows = Math.max(1, Math.ceil(seq.length / cols));

  const S = 2;                          // retina scale
  const W = 720, padX = 40;
  const gridTop = 150, cellH = 70, footerH = 54;
  const cellW = (W - padX * 2) / cols;
  const H = gridTop + rows * cellH + footerH;

  const canvas = document.createElement('canvas');
  canvas.width = W * S;
  canvas.height = H * S;
  const ctx = canvas.getContext('2d');
  ctx.scale(S, S);

  ctx.fillStyle = '#090d1c';
  ctx.fillRect(0, 0, W, H);

  ctx.fillStyle = '#00d4b4';
  ctx.font = '700 20px system-ui, -apple-system, sans-serif';
  ctx.fillText('Jam Pal', padX, 40);

  ctx.fillStyle = '#e4e1f4';
  ctx.font = '700 30px system-ui, -apple-system, sans-serif';
  ctx.fillText('Chord chart', padX, 80);

  const meta = chartMeta(report, timeSig);
  if (meta) {
    ctx.fillStyle = '#5d7099';
    ctx.font = '400 15px system-ui, -apple-system, sans-serif';
    ctx.fillText(meta, padX, 106);
  }

  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  for (let i = 0; i < rows * cols; i++) {
    const r = Math.floor(i / cols), c = i % cols;
    const x = padX + c * cellW, y = gridTop + r * cellH;
    ctx.fillStyle = '#0e1328';
    ctx.fillRect(x, y, cellW, cellH);
    ctx.strokeStyle = '#1e2740';
    ctx.lineWidth = 1;
    ctx.strokeRect(x + 0.5, y + 0.5, cellW, cellH);
    if (seq[i]) {
      ctx.fillStyle = '#e4e1f4';
      ctx.font = '600 22px system-ui, -apple-system, sans-serif';
      ctx.fillText(seq[i], x + cellW / 2, y + cellH / 2 + 1);
    }
  }
  ctx.textAlign = 'left';
  ctx.textBaseline = 'alphabetic';

  ctx.fillStyle = '#5d7099';
  ctx.font = '400 13px system-ui, -apple-system, sans-serif';
  ctx.fillText(`Generated by Jam Pal · ${new Date().toLocaleDateString()}`, padX, H - 22);

  return canvas;
}

function downloadChartPng(report, timeSig) {
  buildChartCanvas(report, timeSig).toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `jam-pal-chart-${new Date().toISOString().slice(0, 10)}.png`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 10000);
  });
}

function ChordChart({ report, timeSig }) {
  const [copied, setCopied] = useState(false);
  const seq = report.chords?.sequence ?? [];

  // pad the last row so the grid stays rectangular
  const padded = [...seq];
  while (padded.length % BARS_PER_ROW !== 0) padded.push('');

  const meta = chartMeta(report, timeSig);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(chordsToText(report, timeSig));
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch { /* clipboard unavailable */ }
  };

  return (
    <div className={styles.progression}>
      <div className={styles.chartHead}>
        <span className={styles.progressionLabel}>Chord chart — what you played</span>
        <div className={styles.exportBtns}>
          <button className={styles.exportBtn} onClick={() => downloadChartPng(report, timeSig)}>
            Download PNG
          </button>
          <button className={styles.exportBtn} onClick={handleCopy}>
            {copied ? 'Copied ✓' : 'Copy'}
          </button>
        </div>
      </div>

      {meta && <div className={styles.chartMeta}>{meta}</div>}

      <div className={styles.chartBars}>
        {padded.map((c, i) => (
          <div key={i} className={`${styles.bar} ${c ? '' : styles.barEmpty}`}>{c}</div>
        ))}
      </div>
    </div>
  );
}

function ReportView({ report, timeSig = '4/4', onDone }) {
  return (
    <div className={styles.page}>
      <div className={styles.header}>
        <div className={styles.logo}>Jam Pal</div>
        <h1 className={styles.title}>Session report</h1>
      </div>

      {!report ? (
        <p className={styles.empty}>
          No data captured this time — play along with the band and your report
          will show up here.
        </p>
      ) : (
        <>
          <div className={styles.grid}>
            <Stat label="Jam time" value={fmtTime(report.durationSec)} />
            {report.timing && (
              <Stat label="In the pocket" value={`${report.timing.pocketPct}%`} sub={pocketSub(report.timing)} />
            )}
            {report.tempo && (
              <Stat label="Tempo" value={`${report.tempo.meanBpm}`} sub={`BPM · steady ${Math.round(report.tempo.steadiness * 100)}%`} />
            )}
            {report.timing && (
              <Stat label="Feel" value={cap(report.timing.tendency)} sub={feelSub(report.timing)} />
            )}
            {report.chords && (
              <Stat label="Chords" value={report.chords.distinct} sub={report.chords.unique.join(' · ')} />
            )}
            {report.energy && (
              <Stat label="Dynamics" value={dynLabel(report.energy.range)} sub={`range ${Math.round(report.energy.range * 100)}%`} />
            )}
          </div>

          {report.chords?.sequence?.length > 0 && (
            <ChordChart report={report} timeSig={timeSig} />
          )}

          <p className={styles.note}>
            AI session feedback will live here soon — for now, these are your raw numbers.
          </p>
        </>
      )}

      <button className={styles.doneBtn} onClick={onDone}>New session</button>
    </div>
  );
}

export default ReportView;
